# Site settings
title: Phobos
header-img: img/home-bg.jpg
email: phobosacademy@gmail.com
copyright_name: Phobos
description: "I can't teach people. I only make them think"
baseurl: ""
url: "phobosacademy.github.io"
twitter_username: 
github_username:  PhobosAcademy
facebook_username:  
email_username:  phobosacademy@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
